title: Computer Engineering
tagline: Rida Insights
description: "A technical blog about computer engineering and writing."
url: "https://ridabatoolsaleem-wq.github.io"
baseurl: "/Rida-blog"

# Settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
